# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I am Wuxinshui # ex. I m Chuan
name: Wuxinshui # ex. DONGChuan
email: rfg2012@163.com
location: shanghai,China # ex. Nice, France
company: QF
company_url: http://wuxinshui.github.io
github_url: https://github.com/wuxinshui # ex. https://github.com/DONGChuan
description: 自由，开源，专业
favicon: favicon.png # Image must be in assets/images
repository: wuxinshui/wuxinshui/wuxinshui.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://wuxinshui.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: henduoshuo.duoshuo.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /link
    label: Link

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 10 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-92426806-1'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, Redis, Boostrap]

#add read book
book_reading:[Effective Java 中文版 第2版, Java程序性能优化-让你的Java程序更快、更稳定]
book_read:[穿布鞋的马云, 软件设计师教程]

